# Generated by Django 2.1.4 on 2018-12-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabooWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_by', models.CharField(default='', max_length=100)),
                ('word', models.CharField(default='', max_length=100)),
                ('is_taboo', models.BooleanField(default=False, verbose_name='Taboo Status')),
            ],
        ),
    ]
