# Generated by Django 2.1.3 on 2018-12-05 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taboo', '0002_auto_20181205_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabooword',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
