# Generated by Django 2.1.3 on 2018-12-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taboo', '0003_auto_20181205_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabooword',
            name='suggested_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
