# Generated by Django 2.1.3 on 2018-11-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181121_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_OU',
            field=models.BooleanField(default=False, verbose_name='OU status'),
        ),
    ]
