# Generated by Django 2.1.3 on 2018-12-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181121_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.CharField(default='', max_length=100),
        ),
    ]
