# Generated by Django 2.1.4 on 2018-12-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181203_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='prof_pic_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
