# Generated by Django 2.1.4 on 2018-12-09 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborators', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=10000)),
                ('private', models.BooleanField(default=False, verbose_name='Private?')),
                ('version', models.IntegerField(default=1)),
                ('locked', models.BooleanField(default=False, verbose_name='Locked Status')),
                ('locked_by', models.IntegerField(blank=True, null=True)),
                ('taboo_index', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('changes', models.CharField(max_length=100)),
                ('updater_ids', models.CharField(default='', max_length=100)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
            ],
        ),
    ]
