# Generated by Django 2.1.4 on 2018-12-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20181208_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='accused',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complainer',
            field=models.IntegerField(editable=False),
        ),
    ]
