# Generated by Django 2.1.3 on 2018-12-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20181210_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='collaborators',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
