# Generated by Django 2.1.3 on 2018-11-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='private',
            field=models.BooleanField(default=False, max_length=100),
        ),
    ]
