# Generated by Django 2.1.3 on 2018-11-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='private',
        ),
        migrations.AddField(
            model_name='document',
            name='classification',
            field=models.CharField(default='public', max_length=100),
        ),
    ]
