# Generated by Django 2.1.3 on 2018-12-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20181210_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='collaborators',
            field=models.CharField(default='', max_length=100),
        ),
    ]
