# Generated by Django 2.1.4 on 2018-12-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20181208_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complainer',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
