# Generated by Django 2.1.3 on 2018-11-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20181130_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='classification',
        ),
        migrations.AddField(
            model_name='document',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Classification'),
        ),
    ]
