# Generated by Django 2.1.4 on 2018-12-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20181208_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='doc',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='documents.Document'),
        ),
    ]
