# Generated by Django 2.1.3 on 2018-11-30 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20181130_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='doc_id',
            new_name='doc',
        ),
    ]
