# Generated by Django 2.1.4 on 2018-12-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20181208_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='message',
        ),
        migrations.AlterField(
            model_name='complaints',
            name='accused',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complainer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document'),
        ),
    ]
