# Generated by Django 2.1.4 on 2018-12-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20181208_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='version',
            field=models.IntegerField(null=True),
        ),
    ]
