# Generated by Django 2.1.3 on 2018-11-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20181130_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='vsn',
            new_name='version',
        ),
    ]
