# Generated by Django 2.1.4 on 2018-12-07 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0013_auto_20181207_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=250)),
                ('accused', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_accused', to=settings.AUTH_USER_MODEL)),
                ('complainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_complainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='updater_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document'),
        ),
    ]
