# Generated by Django 2.1.4 on 2018-12-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_auto_20181207_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='updater_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
