# Generated by Django 2.1.3 on 2018-11-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_OU',
            field=models.BooleanField(default=True, verbose_name='OU status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
